version: "3.9"
services:
  web:
    build: ./web
    container_name: python
    expose:
      - 5000
    env_file:
      - ./.env.prod
    command: gunicorn --workers=3 --bind 0.0.0.0:5000 "app:create_app()"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "1337:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  dbdata:
